In [5]:
import numpy as np
from hmmlearn import hmm
#状态
status=['袋子1','袋子2','袋子3']
obs=['白球','黑球']
n_status=len(status)
m_obs=len(obs)
#起始矩阵
start_pro=np.array([0.2,0.5,0.3])
#状态转移矩阵
transition_pro=np.array([
    [0.5,0.4,0.1],
    [0.2,0.2,0.6],
    [0.2,0.5,0.3],
])
#弹射矩阵
emissioin_pro=np.array([
    [0.4,0.6],
    [0.6,0.2],
    [0.5,0.5],
])

In [22]:
#定义模型
model=hmm.MultinomialHMM(n_components=n_status)
model.startprob_=start_pro
model.transmat_=transition_pro
model.emissionprob_=emissioin_pro
#进行预测
se=np.array([[0,1,0,0,1]]).T
logprob,box_index=model.decode(se,algorithm='viterbi')
print('颜色：',end='')
print(" ".join(map(lambda t:obs[t],[0,1,0,0,1])))
print('袋子序列：',end='')
print(" ".join(map(lambda t:status[t],box_index)))
print('概率值：',end='')
print(np.exp(logprob))

颜色：白球 黑球 白球 白球 黑球
袋子序列：袋子2 袋子3 袋子3 袋子2 袋子3
概率值：0.0012150000000000004


In [23]:
#参数训练，获取状态转移矩阵和弹射矩阵
status=['袋子1','袋子2','袋子3']
obs=['白球','黑球']
n_status=len(status)
m_obs=len(obs)
model2=hmm.MultinomialHMM(n_components=n_status,n_iter=20,tol=0.001)
X2=np.array([
    [0,1,0,0,1],
    [0,0,0,1,1],
    [1,1,0,1,0],
    [0,1,0,1,1],
    [0,0,0,1,0],
])
model2.fit(X2)
print("初始状态：")
print(model2.startprob_)
print("状态转移矩阵：")
print(model2.transmat_)
print("弹射矩阵：")
print(model2.emissionprob_)

初始状态：
[2.01371465e-06 9.99997986e-01 1.31279170e-22]
状态转移矩阵：
[[0.30012623 0.47858025 0.22129352]
 [0.12814653 0.18422413 0.68762934]
 [0.60770658 0.27706372 0.1152297 ]]
弹射矩阵：
[[0.67875466 0.32124534]
 [0.94405943 0.05594057]
 [0.04099108 0.95900892]]
